language: android
sudo: false
jdk: oraclejdk7
env:
  global:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
  matrix:
  - ADB_INSTALL_TIMEOUT=15 ANDROID_BUILD_TOOLS_VERSION=23.0.3 ANDROID_TARGET=android-22
    ANDROID_ABI=armeabi-v7a
cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/gradle/caches/"
  - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
android:
  components:
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - "$ANDROID_TARGET"
  - android-23
  - extra-google-google_play_services
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-$ANDROID_TARGET
before_install:
  - chmod +x gradlew
script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - ./gradlew assembleDebug -PdisablePreDex
  - ./gradlew assembleAndroidTest -PdisablePreDex
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - adb install -r app/build/outputs/apk/app-debug.apk
  - adb install -r app/build/outputs/apk/app-debug-androidTest-unaligned.apk
  - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace --info
  - ./gradlew test --info
after_success:
  - bash <(curl -s https://codecov.io/bash)
